### ISSUE TITLE
Changelog isn't publicly viewable

### ISSUE THREAD

**Issue by T-Spoon** [spatie/laravel-mailcoach-docs#45]
There's a link to the changelog in the docs: https://mailcoach.app/docs/v2/package/general/changelog

But it links to a private repo. 

Maybe that file should be copied to the docs repo? 

The current workaround is to view the changelog from the source code in the `/vendor/spatie/laravel-mailcoach` folder

**Comment by freekmurze** [comment]
In the account section on https://mailcoach.app, you can request access to that repo.

Alternatively, the changelog is also publicly available here: https://mailcoach.app/roadmap
