### ISSUE TITLE
Method parameter is missing

### ISSUE THREAD

**Issue by nessor** [spatie/laravel-mailcoach-docs#55]
Hey guys,

I found [here](https://github.com/spatie/laravel-mailcoach-docs/blob/master/docs/package/working-with-lists/unsubscribing-from-a-list.md) a small error in a sample code.
The method Subscriber::findForEmail requires not only the email address of the user, but also the corresponding email list.

-Florian

**Comment by riasvdv** [comment]
Thanks! Fixed
