### ISSUE TITLE
How do I send a single transactional email to one email address?

### ISSUE THREAD

**Issue by nidheeshdas** [spatie/laravel-mailcoach-docs#71]
I understand this is a email marketing / campaign management system. But I see nowhere it can send a single email with a template. I just want to have a templated email for purposes like Forgot Email, Welcome mail, Order Created; these kinds of emails. I'm not sure how to fit this requirement in the mailcoach.

Was it intentional to keep this kind of thing outside the scope of this project? If so, why? If this is part of the mailcoach, then Mailcoach has the potential to become the complete email solution for a SaaS app.

**Comment by freekmurze** [comment]
This is not possible in the current stable version of Mailcoach.

In mailcoach v4 we'll add support for transactional mails and templating. Expected release Q1/Q2 2021
