### ISSUE TITLE
Old versioned documentation for Configuring Mail Providers

### ISSUE THREAD

**Issue by badasukerubin** [spatie/laravel-mailcoach-docs#78]
Hi, I'm trying to set up mail coach using the documentation and realize it's outdated. take for example https://spatie.be/docs/laravel-mailcoach/v5/configuring-mail-providers/mailgun. Mailcoach doesn't provide the _Mail configuration page_ anymore and I keep running into this error when I try to create campaigns:

`Exception: count(): Argument #1 ($value) must be of type Countable|array, null given (View: /var/www/html/vendor/spatie/laravel-mailcoach/resources/views/app/emailLists/layouts/emailList.blade.php) (View: /var/www/html/vendor/spatie/laravel-mailcoach/resources/views/app/emailLists/layouts/emailList.blade.php);`

**Comment by riasvdv** [comment]
The mail configuration views are part of the spatie/mailcoach-ui package, make sure that package is installed as well if you're using the standalone version.

Otherwise you'll need to configure the mailers manually, for that you can reference https://laravel.com/docs/9.x/mail#configuration

**Comment by badasukerubin** [comment]
I am using it within an existing project. I had to include mailers config in mail.php to solve the issue, something like:

```php
 'mailers' => [
        'mailgun' => [
            'domain' => env('MAILGUN_DOMAIN'),
            'secret' => env('MAILGUN_SECRET'),
            'endpoint' => env('MAILGUN_ENDPOINT', 'api.mailgun.net'),
        ],
  ]
```
